"""Hand-written test suite for GST (India) and US Sales/Use Tax reconciliation.

Per the scoring rubric, tests must be authored directly by team members; tests
generated by LLMs score 0.
"""

from scripts.tax_math import compute_tax_reconciliation


def test_gst_net_liability_basic():
    records = [
        {"type": "sales_invoice", "tax_amount": 1000.0},
        {"type": "purchase_bill", "tax_amount": 400.0, "is_itc_eligible": True, "is_claimed": True},
    ]
    result = compute_tax_reconciliation(records, locale="IN")
    assert result["output_tax_total"] == 1000.0
    assert result["claimed_itc_total"] == 400.0
    assert result["unclaimed_itc_total"] == 0.0
    assert result["net_liability"] == 600.0
    assert result["locale"] == "IN"


def test_unclaimed_itc_isolated():
    records = [
        {"type": "sales_invoice", "tax_amount": 1000.0},
        {"type": "purchase_bill", "tax_amount": 300.0, "is_itc_eligible": True, "is_claimed": False},
    ]
    result = compute_tax_reconciliation(records, locale="IN")
    assert result["unclaimed_itc_total"] == 300.0
    assert result["claimed_itc_total"] == 0.0
    # Unclaimed credit does not reduce net liability until claimed.
    assert result["net_liability"] == 1000.0


def test_ineligible_purchase_excluded():
    records = [
        {"type": "sales_invoice", "tax_amount": 1000.0},
        {"type": "purchase_bill", "tax_amount": 200.0, "is_itc_eligible": False, "is_claimed": False},
    ]
    result = compute_tax_reconciliation(records, locale="IN")
    assert result["claimed_itc_total"] == 0.0
    assert result["unclaimed_itc_total"] == 0.0
    assert result["net_liability"] == 1000.0


def test_net_liability_never_negative():
    records = [
        {"type": "sales_invoice", "tax_amount": 100.0},
        {"type": "purchase_bill", "tax_amount": 500.0, "is_itc_eligible": True, "is_claimed": True},
    ]
    result = compute_tax_reconciliation(records, locale="IN")
    assert result["net_liability"] == 0.0


def test_us_sales_tax_locale_passthrough():
    records = [
        {"type": "sales_invoice", "tax_amount": 250.0},
    ]
    result = compute_tax_reconciliation(records, locale="US")
    assert result["locale"] == "US"
    assert result["output_tax_total"] == 250.0
    assert result["net_liability"] == 250.0
