"""UC-27 — GST return filing timeliness, late fees and interest.

Spec: docs/usecases/IN/uc-27-return-filing-timeliness.md.
Question: "Which GST returns are due or overdue, and what is lateness costing us?"

Statute: GSTR-1 by the 11th (s.37, Rule 59), GSTR-3B by the 20th (s.39, Rule 61); s.47 late fee
₹50/day per return (₹20 nil) up to a turnover-band cap; s.50(1) 18% p.a. interest on the cash paid
late; Rule 59(6) blocks GSTR-1 while the previous 3B is outstanding; Rule 138E blocks e-way bills
after two consecutive missed 3Bs.

Rules:
  return_overdue             unfiled past due: days late, late fee, and for 3B interest on the cash
                             payable (net_tax_payable is null everywhere, so UC-23's computed cash)
  return_filed_late          filed after the due date (historical, same arithmetic)
  return_not_generated       aggregate per return type: closed periods with no return row at all
  eway_block_risk            a 3B outstanding and the next 3B due within 30 days (Rule 138E)
  return_status_meaningless  a GSTR-2B row carrying a filing status or due date (it is generated, not filed)
Day counts are recomputed every run, never stored.
"""

from datetime import date
from decimal import Decimal

from aptax.playbooks.base import Dataset, Playbook, Rule
from scripts.findings import DATA_QUALITY, Finding
from scripts.money import CENTS, fmt, money
from scripts.uc.IN.uc23_period_gst_liability import compute
from scripts.uc.common.dates import add_months, day, period_of, previous_period

FILED = {"filed"}
DUE_DAY = {"GSTR-1": "gstr1_due_day", "GSTR-3B": "gstr3b_due_day"}


def period_key(row) -> str | None:
    rp = str(row.get("return_period") or "")
    return f"{rp[3:]}-{rp[:2]}" if len(rp) == 7 else None


def due_for(rtype: str, period: str, ctx) -> date:
    nxt = add_months(date(int(period[:4]), int(period[5:7]), 1), 1)
    return date(nxt.year, nxt.month, int(ctx.constant(DUE_DAY[rtype])))


def late_fee(days: int, ctx, nil: bool = False) -> Decimal:
    per_day = money(ctx.constant("gst_late_fee_nil_per_day_inr" if nil else "gst_late_fee_per_day_inr"))
    return min(per_day * days, money(ctx.constant("gst_late_fee_cap_inr")))


class FilingTimeliness(Rule):
    id = "return_compliance"
    severity = 70

    def evaluate(self, data: Dataset, ctx):
        rate = Decimal(str(ctx.constant("gst_interest_rate_pct"))) / 100
        rows = data.get("returns", [])
        seen = {(r.get("return_type"), period_key(r)) for r in rows}
        outstanding_3b = []
        for row in rows:
            rtype, period = row.get("return_type"), period_key(row)
            if rtype == "GSTR-2B":
                if row.get("filing_status") or row.get("due_date"):
                    yield Finding(finding_type=DATA_QUALITY, rule="return_status_meaningless", status=DATA_QUALITY,
                                  severity=10, entity_type="GSTReturn", entity_id=row["id"],
                                  entity_ref=f"GSTR-2B {row.get('return_period')}", currency=ctx.currency,
                                  summary=f"GSTR-2B {row.get('return_period')} carries filing_status "
                                          f"'{row.get('filing_status')}' and due date {row.get('due_date')}; GSTR-2B is "
                                          f"generated by the system, never filed, so these fields mean nothing.",
                                  details={"field": "filing_status"})
                continue
            if rtype not in DUE_DAY or not period:
                continue
            due = day(row.get("due_date")) or due_for(rtype, period, ctx)
            filed = day(row.get("filed_date")) if (row.get("filing_status") or "").lower() in FILED else None
            end = filed or ctx.as_of
            days_late = (end - due).days
            if days_late <= 0:
                continue
            fee = late_fee(days_late, ctx)
            interest = Decimal("0.00")
            base = None
            if rtype == "GSTR-3B":
                base = money(row.get("net_tax_payable")) if row.get("net_tax_payable") is not None else \
                    sum(compute(data, ctx, period)["cash"].values(), Decimal("0"))
                interest = (base * rate * days_late / 365).quantize(CENTS)
                if not filed:
                    outstanding_3b.append(period)
            rule = "return_filed_late" if filed else "return_overdue"
            yield Finding(
                finding_type="return_compliance", rule=rule, severity=55 if filed else 80, entity_type="GSTReturn",
                entity_id=row["id"], entity_ref=f"{rtype} {row.get('return_period')}", total_exposure=fee + interest,
                interest_amount=interest, currency=ctx.currency,
                summary=(f"{rtype} {period} " + (f"was filed {days_late} days late on {filed}" if filed else
                                                  f"is {days_late} days overdue (due {due})")
                         + f": late fee {fmt(fee, ctx.currency)}"
                         + (f", interest {fmt(interest, ctx.currency)} on {fmt(base, ctx.currency)} cash" if base else "")
                         + ("" if filed else ", growing daily") + "."),
                details={"return_type": rtype, "period": period, "due_date": str(due), "days_late": days_late,
                         "late_fee": str(fee), "interest_amount": str(interest),
                         "interest_base": str(base) if base is not None else None,
                         "interest_base_source": None if base is None else (
                             "net_tax_payable" if row.get("net_tax_payable") is not None else "UC-23 computed cash")})
        first = min((period_of(i.get("date")) for i in data.get("invoices", []) if period_of(i.get("date"))), default=None)
        last_closed = previous_period(ctx.as_of)
        if first:
            for rtype in DUE_DAY:
                missing, p = [], first
                while p <= last_closed:
                    if (rtype, p) not in seen:
                        missing.append(p)
                    d = add_months(date(int(p[:4]), int(p[5:7]), 1), 1)
                    p = f"{d.year:04d}-{d.month:02d}"
                if missing:
                    overdue = [m for m in missing if due_for(rtype, m, ctx) < ctx.as_of]
                    yield Finding(
                        finding_type="return_compliance", rule="return_not_generated", severity=60,
                        entity_type="GSTReturn", entity_id=f"{rtype}:missing", entity_ref=f"{rtype} (no row)",
                        currency=ctx.currency,
                        summary=f"No {rtype} row exists for {len(missing)} closed period(s) since the ledger starts "
                                f"({missing[0]} … {missing[-1]}); {len(overdue)} are past their due date. Either they "
                                f"were filed outside the platform or they are outstanding.",
                        details={"return_type": rtype, "periods": missing, "past_due": overdue})
        # the next 3B to fall due is the one for the last closed month
        nxt = previous_period(ctx.as_of)
        next_due = due_for("GSTR-3B", nxt, ctx)
        filed_next = any(r.get("return_type") == "GSTR-3B" and period_key(r) == nxt
                         and (r.get("filing_status") or "").lower() in FILED for r in rows)
        if outstanding_3b and nxt not in outstanding_3b and not filed_next and 0 <= (next_due - ctx.as_of).days <= 30:
            yield Finding(
                finding_type="return_compliance", rule="eway_block_risk", severity=85, entity_type="GSTReturn",
                entity_id=f"eway:{nxt}", entity_ref=f"GSTR-3B {nxt}", currency=ctx.currency,
                summary=f"GSTR-3B for {', '.join(outstanding_3b)} is outstanding; missing {nxt} on {next_due} makes "
                        f"two consecutive periods and blocks e-way bill generation (Rule 138E). GSTR-1 for the next "
                        f"period also can't be filed until the 3B is (Rule 59(6)).",
                details={"outstanding_3b": outstanding_3b, "next_3b_due": str(next_due)})


class ReturnFilingTimeliness(Playbook):

    @property
    def rules(self):
        return [FilingTimeliness()]

    def fetch(self, ctx, fetcher) -> Dataset:
        return Dataset(returns=fetcher.list("GSTReturn"), invoices=fetcher.list("Invoice"),
                       credit_notes=fetcher.list("CreditNote"), bills=fetcher.list("Bill"),
                       vendor_credits=fetcher.list("VendorCredit"), parties=fetcher.list("Party"),
                       items=fetcher.list("Item"))

    def context(self, data, findings, ctx):
        return {"return rows": [f"{r.get('return_type')} {r.get('return_period')} {r.get('filing_status')}"
                                for r in data["returns"]],
                "late-fee cap used": str(money(ctx.constant("gst_late_fee_cap_inr"))),
                "filing frequency": "monthly (locale)"}

    def summary(self, outcome, ctx):
        over = [f for f in outcome.findings if f.rule == "return_overdue"]
        fee = sum((money(f.details["late_fee"]) for f in over), Decimal("0"))
        interest = sum((f.interest_amount for f in over), Decimal("0"))
        risk = any(f.rule == "eway_block_risk" for f in outcome.findings)
        names = ", ".join(f"{f.entity_ref} ({f.details['days_late']} days)" for f in over)
        return ((f"{len(over)} return(s) overdue: {names}; {fmt(fee, ctx.currency)} late fee and "
                 f"{fmt(interest, ctx.currency)} interest so far, growing daily." if over else "No return is overdue.")
                + (" Missing the next GSTR-3B blocks e-way bills (Rule 138E)." if risk else ""))
